name: Push dictionary.json to Gitee on update

on:
  push:
分支:
      - main
    paths:
      - 'dictionary.json'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: ${{ secrets.GITEE_REPO }}
          path: gitee-repo
          ref: ${{ secrets.GITEE_BRANCH }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          python3 -c "
          import urllib.parse
          with open('dictionary.json', encoding='utf-8') as f:
              raw = f.read()
          encoded = urllib.parse.quote(raw, safe='')
          with open('gitee-repo/json/dictionary.json', 'w', encoding='utf-8') as f:
              f.write(encoded)
          "

      - working-directory: gitee-repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add json/dictionary.json
          git diff --cached --quiet && exit 0
          git commit -m "chore: auto sync & urlencode dictionary.json"
          git push https://${{ secrets.GITEE_USER }}:${{ secrets.GITEE_PASSWORD }}@gitee.com/${{ secrets.GITEE_REPO }}.git ${{ secrets.GITEE_BRANCH }}
