name: Sync dictionary.json to Gitee on update

on:
  push:
    branches:
      - main
    paths:
      - 'dictionary.json'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出源仓库（GitHub）
      - name: Checkout source repo
        uses: actions/checkout@v4

      # 2. 检出 Gitee 目标仓库（用令牌避免终端提示）
      - name: Checkout Gitee repo
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.GITEE_REPO }}   # 填 owner/repo 即可
          token: ${{ secrets.GITEE_TOKEN }}       # Gitee 私人令牌
          path: gitee-repo
          ref: ${{ secrets.GITEE_BRANCH }}        # 如 master

      # 3. URL 编码并覆盖
      - name: URL-encode dictionary.json
        run: |
          python3 <<'EOF'
          import urllib.parse, os
          with open('dictionary.json', encoding='utf-8') as f:
              raw = f.read()
          encoded = urllib.parse.quote(raw, safe='')
          os.makedirs('gitee-repo/json', exist_ok=True)
          with open('gitee-repo/json/dictionary.json', 'w', encoding='utf-8') as f:
              f.write(encoded)
          EOF

      # 4. 提交并推送（令牌直接嵌在 URL，禁用终端也不会再问）
      - name: Commit & push to Gitee
        working-directory: gitee-repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add json/dictionary.json
          git diff --cached --quiet && exit 0
          git commit -m "chore: auto sync & urlencode dictionary.json"
          # 下面一行已带令牌，无需交互
          git push \
            https://${{ secrets.GITEE_TOKEN }}@gitee.com/${{ secrets.GITEE_REPO }}.git \
            ${{ secrets.GITEE_BRANCH }}
