      - name: 3. URL-encode dictionary.json (with debug)
        shell: bash
        run: |
          set -ex
          python3 <<'EOF'
import urllib.parse, os, sys
infile  = 'dictionary.json'
outfile = 'gitee-repo/json/dictionary.json'
if not os.path.exists(infile):
    sys.stderr.write(f'❌ 源文件 {infile} 不存在\n')
    sys.exit(1)
with open(infile, encoding='utf-8') as f:
    raw = f.read()
encoded = urllib.parse.quote(raw, safe='')
os.makedirs(os.path.dirname(outfile), exist_ok=True)
with open(outfile, 'w', encoding='utf-8') as f:
    f.write(encoded)
print(f'✅ 已生成 {outfile}')
EOF
