name: Sync dictionary.json to Gitee on update

on:
  push:
    branches:
      - main
    paths:
      - 'dictionary.json'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout source repo
        uses: actions/checkout@v4

      - name: 2. Fetch Gitee repo (with debug)
        shell: bash
        run: |
          set -ex
          git clone \
            https://${{ secrets.GITEE_TOKEN }}@gitee.com/${{ secrets.GITEE_REPO }}.git \
            gitee-repo -b ${{ secrets.GITEE_BRANCH }} || {
              echo "==== 克隆失败，这里捕获 ===="
              exit 1
            }

      - name: 3. URL-encode dictionary.json (with debug)
        shell: bash
        run: |
          set -ex
          python3 <<'EOF'
import urllib.parse, os, sys
infile  = 'dictionary.json'
outfile = 'gitee-repo/json/dictionary.json'
if not os.path.exists(infile):
    sys.stderr.write(f'❌ 源文件 {infile} 不存在\n')
    sys.exit(1)
with open(infile, encoding='utf-8') as f:
    raw = f.read()
encoded = urllib.parse.quote(raw, safe='')
os.makedirs(os.path.dirname(outfile), exist_ok=True)
with open(outfile, 'w', encoding='utf-8') as f:
    f.write(encoded)
print(f'✅ 已生成 {outfile}')
EOF

      - name: 4. Commit & push to Gitee (with debug)
        shell: bash
        working-directory: gitee-repo
        run: |
          set -ex
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add json/dictionary.json
          if git diff --cached --quiet; then
            echo "==> 文件无变化，跳过提交"
            exit 0
          fi
          git commit -m "chore: auto sync & urlencode dictionary.json"
          git push \
            https://${{ secrets.GITEE_TOKEN }}@gitee.com/${{ secrets.GITEE_REPO }}.git \
            ${{ secrets.GITEE_BRANCH }}
